---
title: "Remote_Sensing_GoogleEarthStudio_Tutorial"
author: "Elizabeth Madin"
date: "5/21/2021"
output: html_document
---

## Summary 

Tutorial on key features of Google Earth Studio. 

## Goals

* Gain familiarity with making 3D, geospatial movies. 
* Consider how you can use this tool in communicating your own research.

## Components

#### Making a simple movie  

* Using Chrome browser (required), sign in to [Google Earth Studio](https://www.google.com/earth/studio/)
* Click "Try Earth Studio"
* Click drop-down arrow next to "Blank Project"
* Choose "Quick Starts"
* Hover over the options for previews and choose one you'd like to make
* Click on the one you want, then click "Start"
* Follow the prompts; here's an example of steps if you're doing a Point-toPoint movie:
    + Type in your first location in the search box
    + Click the right hand arrow to choose your next location and so on
    + When finished, click "Render" & then save

#### Making a fancier movie

* Repeat the steps above again, but try modifying the settings to customize it a bit more

